CREATE TABLE ADDRESS(
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  addressUnumbered VARCHAR(255),
  number VARCHAR(255)
);

CREATE TABLE SUPPLIER(
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  firstname VARCHAR(255),
  lastname VARCHAR(255),
  companyname VARCHAR(255),
  vat VARCHAR(255),
  irs VARCHAR(255),
  city VARCHAR(255),
  country VARCHAR(255),
  address_id BIGINT,
  FOREIGN KEY(address_id) REFERENCES ADDRESS(id)
);